In [11]:
import numpy as np

Importing the dependencies

In [12]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

#Import the model
from model import LogisticRegression

Data Collection and Analysis

PIMA Diabetes dataset

In [13]:
#loading the dataset in a pandas data frame
diabetes_dataset = pd.read_csv('../Logistic_Regression/dataset/diabetes.csv')

In [14]:
diabetes_dataset.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [15]:
#Dimensions of dataset
diabetes_dataset.shape

(768, 9)

In [16]:
#Getting the statistical measures
diabetes_dataset.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [17]:
#Getting the data distribution
diabetes_dataset['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [18]:
#group by outcome, select the aggregate measures
diabetes_dataset.groupby('Outcome').mean()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,3.298000,109.980000,68.184000,19.664000,68.792000,30.304200,0.429734,31.190000
1,4.865672,141.257463,70.824627,22.164179,100.335821,35.142537,0.550500,37.067164

In [19]:
#Separating the data and labels
X = diabetes_dataset.drop('Outcome', axis = 1)
Y = diabetes_dataset['Outcome']

In [20]:
print(X)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6
1              1       85             66             29        0  26.6
2              8      183             64              0        0  23.3
3              1       89             66             23       94  28.1
4              0      137             40             35      168  43.1
..           ...      ...            ...            ...      ...   ...
763           10      101             76             48      180  32.9
764            2      122             70             27        0  36.8
765            5      121             72             23      112  26.2
766            1      126             60              0        0  30.1
767            1       93             70             31        0  30.4

     DiabetesPedigreeFunction  Age
0                       0.627   50
1                       0.351   31
2                       0.672   32
3                       0.167   21
4                       2.288   33
..                        ...  ...
763                     0.171   63
764                     0.340   27
765                     0.245   30
766                     0.349   47
767                     0.315   23

[768 rows x 8 columns]

In [21]:
print(Y)

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

**Split the data in training and testing**

In [22]:
#stratify -> keeps the ratio of outcome 0:1 same for original, test data and training data
train_X, test_X, train_Y, test_Y = train_test_split(X, Y, test_size = 0.3, stratify = Y, random_state = 2)

**Data Standardization**

In [23]:
#Call the constructor StandardScaler()
scaler = StandardScaler()

In [24]:
#Fit the mean and standard deviation **for each column**
scaler.fit(train_X)

StandardScaler()

In [25]:
#Transform training and testing data using the measures
#of training data only to avoid data leakage (learning future)
train_X = scaler.transform(train_X)
test_X = scaler.transform(test_X)

In [26]:
print(X.shape, train_X.shape, test_X.shape)

(768, 8) (537, 8) (231, 8)

**Training the model**

In [27]:
classifier = LogisticRegression(learning_rate = 0.01, number_of_iterations = 1000)

In [28]:
classifier.fit(train_X, train_Y)

**Model Evaluation**

Accuracy Score

In [29]:
#Accuracy score on training data
X_train_prediction = classifier.predict(train_X)
training_data_accuracy = accuracy_score(X_train_prediction, train_Y)

In [30]:
print('Accuracy score on training data: ', training_data_accuracy)

Accuracy score on training data:  0.7728119180633147

In [31]:
#Accuracy score on test data
X_test_prediction = classifier.predict(test_X)
test_data_accuracy = accuracy_score(X_test_prediction, test_Y)

In [32]:
print('Accuracy score on test data: ', test_data_accuracy)

Accuracy score on test data:  0.7792207792207793